[build]
  publish = "." # Root directory where your HTML files are located
  functions = "netlify/v1/functions" # Correct path to your serverless functions

[functions]
  directory = "netlify/v1/functions" # Matches the structure in your project

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200